AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy an EKS cluster, with users and roles mapped to aws-auth.
Resources:
  EKSQuickStart:
    Type: AWS::CloudFormation::TypeActivation
    Properties: 
      AutoUpdate: true
      PublicTypeArn: !Sub 'arn:aws:cloudformation:${AWS::Region}::type/resource/408988dff9e863704bcc72e7e13f8d645cee8311/AWSQS-EKS-Cluster' # Depends on which region they are going to deploy